// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ProjectDbFirst.Models;

namespace ProjectDbFirst.Contexts
{
    public partial class EMPLOYEESContext : DbContext
    {

        public EMPLOYEESContext(DbContextOptions<EMPLOYEESContext> options)
            : base(options)
        {
        }

        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Dept> Depts { get; set; }
        public virtual DbSet<Emp> Emps { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<City>(entity =>
            {
                entity.HasOne(d => d.C)
                    .WithMany(p => p.Cities)
                    .HasForeignKey(d => d.CId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_City_Country");
            });

            modelBuilder.Entity<Emp>(entity =>
            {
                entity.HasOne(d => d.Cty)
                    .WithMany(p => p.Emps)
                    .HasForeignKey(d => d.CtyId)
                    .HasConstraintName("FK_Emps_City");

                entity.HasOne(d => d.D)
                    .WithMany(p => p.Emps)
                    .HasForeignKey(d => d.DId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Emps_Depts");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}