// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectDbFirst.Models
{
    [Table("City")]
    public partial class City
    {
        public City()
        {
            Emps = new HashSet<Emp>();
        }

        [Key]
        [Column("cityID")]
        public int CityId { get; set; }
        [Required]
        [StringLength(50)]
        public string CityName { get; set; }
        [Column("cID")]
        public int CId { get; set; }

        [ForeignKey(nameof(CId))]
        [InverseProperty(nameof(Country.Cities))]
        public virtual Country C { get; set; }
        [InverseProperty(nameof(Emp.Cty))]
        public virtual ICollection<Emp> Emps { get; set; }
    }
}