// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectDbFirst.Models
{
    [Table("Country")]
    public partial class Country
    {
        public Country()
        {
            Cities = new HashSet<City>();
        }

        [Key]
        [Column("countryID")]
        public int CountryId { get; set; }
        [Required]
        [StringLength(50)]
        public string CountryName { get; set; }

        [InverseProperty(nameof(City.C))]
        public virtual ICollection<City> Cities { get; set; }
    }
}