// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectDbFirst.Models
{
    public partial class Dept
    {
        public Dept()
        {
            Emps = new HashSet<Emp>();
        }

        [Key]
        [Column("DeptID")]
        public int DeptId { get; set; }
        [Required]
        [StringLength(50)]
        public string DeptName { get; set; }
        [StringLength(50)]
        public string DeptDesc { get; set; }

        [InverseProperty(nameof(Emp.D))]
        public virtual ICollection<Emp> Emps { get; set; }
    }
}